settings:
  start-cooldown-in-second: 300
  start-cooldown-messages-in-second:
    - 300
    - 240
    - 180
    - 120
    - 60
    - 30
    - 15
    - 10
    - 9
    - 8
    - 7
    - 6
    - 5
    - 4
    - 3
    - 2
    - 1
  # PLAYER | FACTION | GANG | SKYBLOCK
  participant-type: PLAYER


scoreboard:
  enabled: true
  check-distance-to-apply: false
  distance-to-apply-value: 20
  name: "&c☀ TheSyncTowers ☀"
  lines-type-point:
    - "&3 "
    - "&dName: &a%towersync_name%"
    - "&dGoal: &a%towersync_goal%"
    - "&c "
    - "&eClassement:"
    - "&f "
    - "&6> 1. &e%towersync_top_1% &6%towersync_top_1_points%"
    - "&6> 2. &e%towersync_top_2% &6%towersync_top_2_points%"
    - "&6> 3. &e%towersync_top_3% &6%towersync_top_3_points%"
    - "..."
    - "&6> %towersync_player_top%. &eYou"
  lines-type-time:
    - "&3 "
    - "&dName: &a%towersync_name%"
    - "&dTime Remaining: &a%runningtowersync_timeremaining%"
    - "&c "
    - "&eClassement:"
    - "&f "
    - "&6> 1. &e%towersync_top_1% &6%towersync_top_1_points%"
    - "&6> 2. &e%towersync_top_2% &6%towersync_top_2_points%"
    - "&6> 3. &e%towersync_top_3% &6%towersync_top_3_points%"
    - "..."
    - "&6> %towersync_player_top%. &eYou"