license-key: "PUT_YOUR_LICENSE_HERE"
settings:
  start-cooldown-in-second: 300
  start-cooldown-messages-in-second:
    - 300
    - 240
    - 180
    - 120
    - 60
    - 30
    - 15
    - 10
  # PLAYER | FACTION | GANG | SKYBLOCK
  participant-type: PLAYER
  items-restriction:
    restriction: true
    # WHITELIST | BLACKLIST
    restriction-type: WHITELIST
    items:
      - "DIAMOND_SWORD"
      - "IRON_SWORD"
      - "GOLDEN_SWORD"
      - "WOODEN_SWORD"


scoreboard:
  enabled: true
  check-distance-to-apply: false
  distance-to-apply-value: 20
  name: "&f☀ &3TheSyncTowers &f☀"
  lines-type-point:
    - "&7&m---------------------------"
    - "&3Name: &b%towersync_name%"
    - "&3Goal: &b%towersync_goal%"
    - "&c "
    - "&bClassement:"
    - "&f "
    - " &b1• &f%towersync_top_1% &f%towersync_top_1_points%"
    - " &b2• &f%towersync_top_2% &f%towersync_top_2_points%"
    - " &b3• &f%towersync_top_3% &f%towersync_top_3_points%"
    - "&c&e "
    - "&3&l» &b%towersync_player_top%. &3You"
    - "&f&7&m---------------------------"
  lines-type-time:
    - "&7&m---------------------------"
    - "&3Name: &b%towersync_name%"
    - "&3Time Remaining: &b%runningtowersync_timeremaining%"
    - "&c "
    - "&bClassement:"
    - "&f "
    - " &b1• &f%towersync_top_1% &f%towersync_top_1_points%"
    - " &b2• &f%towersync_top_2% &f%towersync_top_2_points%"
    - " &b3• &f%towersync_top_3% &f%towersync_top_3_points%"
    - "&c&e "
    - "&3&l» &b%towersync_player_top%. &3You"
    - "&f&7&m---------------------------"