name: TheSyncTowers
version: @version@
main: fr.customentity.thesynctowers.TheSyncTowers
api-version: 1.16
authors: [ CustomEntity ]
softdepend: [ FeatherBoard, Factions ]
description: Suitable for a faction pvp server that wants to add an event.
commands:
  thesynctowers:
    aliases: [ tst ]
